# Generated by Django 6.0.6 on 2026-07-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_entity_instancedentity_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='avatar_id',
            field=models.IntegerField(default=4),
        ),
    ]
