# Generated by Django 6.0.6 on 2026-07-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_actor_avatar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.IntegerField(unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('RespawnTimer', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='IsAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
