# Generated by Django 6.0.6 on 2026-07-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_worldnode_user_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldnode',
            name='node_type',
            field=models.IntegerField(),
        ),
    ]
