# Generated by Django 6.0.6 on 2026-07-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_worldnode_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldnode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
