# Generated by Django 6.0.6 on 2026-07-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_worldnode_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancedentity',
            name='Rocks',
            field=models.IntegerField(default=0),
        ),
    ]
