# Generated by Django 6.0.7 on 2026-08-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_instancedentity_rocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancedentity',
            name='purchased_upgrades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
